networks:
  media:
    driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - media
    ports:
      - 8096:8096  # Web UI
      - 8920:8920  # HTTPS
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      # Mount the host's hard drives directly into the container
      - /mnt/media1:/media1
      - /mnt/media2:/media2
      - ./media:/media
      # Local configuration and cache directories
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./radarr/config:/config
      - ./media/movies:/movies
      - ./media/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./sonarr/config:/config
      - ./media/tv:/tv
      - ./media/downloads:/downloads
    restart: unless-stopped

  # --- Nextcloud Setup ---
  db:
    image: mariadb:10.6
    container_name: nextcloud-db
    networks:
      - media
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    volumes:
      - ./nextcloud/db:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    networks:
      - media
    ports:
      - 8081:80   # Web UI for Nextcloud
    links:
      - db
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
    volumes:
      - ./nextcloud/config:/config
      - ./nextcloud/data:/data
      # Mount the same HDDs you use for Jellyfin
      - /mnt/media1:/mnt/media1
      - /mnt/media2:/mnt/media2
