version: "3.9"

networks:
  media:
    driver: bridge

services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - media
    ports:
      - 8096:8096  # Web UI
      - 8920:8920  # HTTPS
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      # Mount the host's hard drives directly into the container
      - /mnt/media1:/media1
      - /mnt/media2:/media2
      - ./media:/media
      # Local configuration and cache directories
      - ./jellyfin/config:/config
      - ./jellyfin/cache:/cache
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    networks:
      - media
    ports:
      - 8080:8080  # Web UI
      - 6881:6881
      - 6881:6881/udp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
      - WEBUI_PORT=8080
    volumes:
      - ./qbittorrent/config:/config
      - ./media/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    networks:
      - media
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./radarr/config:/config
      - ./media/movies:/movies
      - ./media/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - media
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Vancouver
    volumes:
      - ./sonarr/config:/config
      - ./media/tv:/tv
      - ./media/downloads:/downloads
    restart: unless-stopped